# Site settings
title: Don Irby
email: donirby@live.com
description: A dynamically generated hierarchical menu in jekyll without plugins
baseurl: "/jekyll-dynamic-menu-don-irby"
url: "http://donirby.github.io/jekyll-dynamic-menu-don-irby"
github_username:  donirby
